      common/c2/astar,bstar,cstar,e0,ph,pk,pl,
     .         t,yi,pi,h,k,l,alamda,          
     .         thetao,dtheta,ntheta,nscan,bhx,bhy,bhz,thetx,thetax,                    
     .         to,esse,sintb,costb,thetab,kprp,kpar,                    
     .         alpha,zzeta,zz1,zz2,                      
     .         xi,zi,bi,g0,eo,phio,mh,mk,ml,phi,psi,psio,  
     .         ipvec,iter,isinv,ncal,isprp,ispar,ifac,iphi,   
     .         izscan,nz,ik,jflag,kflag,nprint,n                              
